export const SET_LOADING = "SET_LOADING";

// SERVICES
export const FETCH_ALL_SERVICE = "FETCH_ALL_SERVICE";
export const FETCH_ALL_SERVICE_SUCCESS = "FETCH_ALL_SERVICE_SUCCESS";
export const FETCH_ALL_SERVICE_ERROR = "FETCH_ALL_SERVICE_ERROR";

// OPERATORS
export const FETCH_ALL_OPERATOR = "FETCH_ALL_OPERATOR";
