const routes = {
  home: "/",
  login: "/login",
  register: "/register",
  forgot: "/forgot-password",
  reset: "/reset-password",
  verify: "/verify-email",
  profile: "/profile",
  terms: "/terms-condition",
  policy: "/privacy-policy",
  faq: "/faq",
  notFound: "/404",
  contactUs: "/contact-us",
  aboutUs: "/about-us",
  refer: "/refer",
  service: "/service",
  service2: "/service2",
  support: "/support",
  profileDashboard: "/profile-dashboard",
  profileTransaction: "/transaction",
  profileWalletHistory: "/wallet-history",
  profileChangePassword: "/change-password",
  profileChangePin: "/change-pin",
  otp: "/otp",
  wallet: "/wallet",
};

export default routes;
