export const FETCH_ALL_TRANSACTION_LIST = "FETCH_ALL_TRANSACTION_LIST";
export const SET_LOADING_TRANSACTION = "SET_LOADING_TRANSACTION";
export const SET_SIZE_PER_PAGE_TRANSACTION = "SET_SIZE_PER_PAGE_TRANSACTION";
export const SET_PAGE_TRANSACTION = "SET_PAGE_TRANSACTION";
export const SET_SEARCH_TRANSACTION = "SET_SEARCH_TRANSACTION";
export const SET_SORT_FIELD_TRANSACTION = "SET_SORT_FIELD_TRANSACTION";
export const SET_SORT_ORDER_TRANSACTION = "SET_SORT_ORDER_TRANSACTION";
