export const SET_LOADING_WALLET = "SET_LOADING_WALLET";

// SERVICES
export const FETCH_ALL_WALLET_LIST = "FETCH_ALL_WALLET_LIST";

export const SET_SIZE_PER_PAGE_WALLET = "SET_SIZE_PER_PAGE_WALLET";
export const SET_PAGE_WALLET = "SET_PAGE_WALLET";
export const SET_SEARCH_WALLET = "SET_SEARCH_WALLET";
export const SET_SORT_FIELD_WALLET = "SET_SORT_FIELD_WALLET";
export const SET_SORT_ORDER_WALLET = "SET_SORT_ORDER_WALLET";
