export const FETCH_ALL_RECHARGE_LIST = "FETCH_ALL_RECHARGE_LIST";
export const SET_LOADING_RECHARGES = "SET_LOADING_RECHARGES";
export const SET_SIZE_PER_PAGE_RECHARGE = "SET_SIZE_PER_PAGE_RECHARGE";
export const SET_PAGE_RECHARGE = "SET_PAGE_RECHARGE";
export const SET_SEARCH_RECHARGE = "SET_SEARCH_RECHARGE";
export const SET_SORT_FIELD_RECHARGE = "SET_SORT_FIELD_RECHARGE";
export const SET_SORT_ORDER_RECHARGE = "SET_SORT_ORDER_RECHARGE";
