// Va 10 - 01 - 21

export const SET_PROFILE = "SET_PROFILE";
export const SET_PROFILE_LOADING = "SET_PROFILE_LOADING";
export const SET_USERNAME = "SET_USERNAME";

// GET ACTIVE MEMBERSHIPS
export const FETCH_ACTIVE_MEMBERSHIPS = "FETCH_ACTIVE_MEMBERSHIPS";
export const FETCH_ACTIVE_MEMBERSHIPS_SUCCESS =
  "FETCH_ACTIVE_MEMBERSHIPS_SUCCESS";
export const FETCH_ACTIVE_MEMBERSHIPS_ERROR = "FETCH_ACTIVE_MEMBERSHIPS_ERROR";

// SAVE BILLING SHIPPING ADDRESS
export const SAVE_ADDRESS = "SAVE_ADDRESS";
export const SAVE_ADDRESS_SUCCESS = "SAVE_ADDRESS_SUCCESS";
export const SAVE_ADDRESS_ERROR = "SAVE_ADDRESS_ERROR";

// GET ACTIVE MEMBERSHIPS
export const FETCH_VOLUMES_MEMBERSHIPS = "FETCH_VOLUMES_MEMBERSHIPS";
export const FETCH_VOLUMES_MEMBERSHIPS_SUCCESS =
  "FETCH_VOLUMES_MEMBERSHIPS_SUCCESS";
export const FETCH_VOLUMES_MEMBERSHIPS_ERROR =
  "FETCH_VOLUMES_MEMBERSHIPS_ERROR";

//user data
export const SET_USER_WALLET_DATA = "SET_USER_WALLET_DATA";
export const SET_USER_WALLET_LISTING = "SET_USER_WALLET_LISTING";
export const SET_USER_TRANSACTION_LISTING = "SET_USER_TRANSACTION_LISTING";

export const RESET = "RESET";

// --------------------
export const FETCH_BANK_LIST = "FETCH_BANK_LIST";



//Activity

export const GET_ACTIVITY_LOADING = "GET_ACTIVITY_LOADING"
export const GET_ACTIVITY = "GET_ACTIVITY"
